<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="2" parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="2" parallel="tests" name="Test2(failed)">
    <classes>
      <class name="vTiger.organisationTest.toCreateOrganizationTest">
        <methods>
          <include name="beforeMethodConfig"/>
          <include name="beforeSuiteConfig"/>
          <include name="afterSuitConfig"/>
          <include name="toCreateOrganizationTest_002"/>
          <include name="beforeClassConfig"/>
          <include name="afterClass"/>
          <include name="afterMethodConfig"/>
        </methods>
      </class> <!-- vTiger.organisationTest.toCreateOrganizationTest -->
    </classes>
  </test> <!-- Test2(failed) -->
  <test thread-count="2" parallel="tests" name="Test1(failed)">
    <classes>
      <class name="vTiger.ContactTests.toCreateContactTest">
        <methods>
          <include name="beforeMethodConfig"/>
          <include name="beforeSuiteConfig"/>
          <include name="toCreateContactTest_001"/>
          <include name="afterSuitConfig"/>
          <include name="beforeClassConfig"/>
          <include name="afterClass"/>
          <include name="afterMethodConfig"/>
        </methods>
      </class> <!-- vTiger.ContactTests.toCreateContactTest -->
    </classes>
  </test> <!-- Test1(failed) -->
</suite> <!-- Failed suite [Suite] -->
